name: FTP Upload via sftp with sshpass

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.strato.de >> ~/.ssh/known_hosts

      - name: Upload files to SFTP Server
        env:
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ssh.strato.de
          LOCAL_DIR: "./test/"
          REMOTE_DIR: "/webapp/public/"
        run: |
          echo "Remote-Verzeichnis Listing:"
          sshpass -p "$FTP_PASS" sftp -v "$FTP_USER@$FTP_SERVER" <<EOF
          ls $REMOTE_DIR
          bye
          EOF
          
          echo "Beginne Upload von $LOCAL_DIR nach $REMOTE_DIR..."
          sshpass -p "$FTP_PASS" sftp -v "$FTP_USER@$FTP_SERVER" <<EOF
          lcd $LOCAL_DIR
          cd $REMOTE_DIR
          mput -r *
          bye
          EOF
          echo "Upload erfolgreich abgeschlossen!"
